version: '3.5'

services:
  node:
    container_name: ${PROJECT_NAME}_node
    build:
      context: .
      dockerfile: ./.deployment/docker/containers/node/Dockerfile
    volumes:
      - ./:/srv/app
    stdin_open: true
    environment:
      NODE_ENV: development
    tty: true
    networks:
      - service
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.gas_front.rule=Host(`front.traefik.me`)"
      - "traefik.http.routers.gas_front.tls=true"
      - "traefik.http.services.gas_front.loadbalancer.server.port=3000"

networks:
  service:
    name: service
    external: true
  traefik:
    name: traefik
    external: true
